### PR TITLE
feat: Available set eventTypes when create alerts.

### PR DESCRIPTION
**Pull request by eugeniykurasov**
When you create dataset: events. By default he create eventTypes:['errors'].
So you can't create alerts with event_type: default or both.

### CODE REVIEW

**Comment by eugeniykurasov** [comment]
@jianyuan Hi, can you please merge and release. 

I need this changes for terraform-provider-sentry.

**Comment by jianyuan** [comment]
Looks good to me, thanks @eugeniykurasov!

**Comment by eugeniykurasov** [comment]
Can you please create new release? Thanks

**Comment by jianyuan** [comment]
I've tagged the release as v2.1.0

**Pull request merged**
